version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: Diablo.sln
  verbosity: minimal
artifacts:
  - path: Source\WinRel\Diablo.exe
    name: Diablo.exe
